{{config(materialized='view', tags='football',enabled=false)}}


SELECT
	match_key
	,GameNumber
	,GameWeek
	,CAST(MatchDay AS DATE)    AS MatchDay
	,MatchTime
	,Season
	,Country
	,REPLACE(REPLACE(League,' "',''),'"','') AS League
	,Division
	,HomeTeam
	,AwayTeam
	,CASE WHEN Referee			='NULL' THEN NULL ELSE Referee				END AS Referee
	,CASE WHEN FullTimeHomeGoal	='NULL' THEN NULL ELSE FullTimeHomeGoal		END AS FullTimeHomeGoal
	,CASE WHEN FullTimeAwayGoal	='NULL' THEN NULL ELSE FullTimeAwayGoal		END AS FullTimeAwayGoal
	,CASE WHEN FullTimeResult	='NULL' THEN NULL ELSE FullTimeResult		END AS FullTimeResult
	,CASE WHEN HalfTimeHomeGoal	='NULL' THEN NULL ELSE HalfTimeHomeGoal		END AS HalfTimeHomeGoal
	,CASE WHEN HalfTimeAwayGoal	='NULL' THEN NULL ELSE HalfTimeAwayGoal		END AS HalfTimeAwayGoal
	,CASE WHEN HalfTimeResult	='NULL' THEN NULL ELSE HalfTimeResult		END AS HalfTimeResult
	,CASE WHEN HomeShots		='NULL' THEN NULL ELSE HomeShots			END AS HomeShots
	,CASE WHEN AwayShots		='NULL' THEN NULL ELSE AwayShots			END AS AwayShots
	,CASE WHEN HomeShotTarget	='NULL' THEN NULL ELSE HomeShotTarget		END AS HomeShotTarget
	,CASE WHEN AwayShotTarget	='NULL' THEN NULL ELSE AwayShotTarget		END AS AwayShotTarget
	,CASE WHEN HomeFouls		='NULL' THEN NULL ELSE HomeFouls			END AS HomeFouls
	,CASE WHEN AwayFouls		='NULL' THEN NULL ELSE AwayFouls			END AS AwayFouls
	,CASE WHEN HomeFoulsConceded='NULL' THEN NULL ELSE HomeFoulsConceded	END AS HomeFoulsConceded
	,CASE WHEN AwayFoulsConceded='NULL' THEN NULL ELSE AwayFoulsConceded	END AS AwayFoulsConceded
	,CASE WHEN HomeCorners		='NULL' THEN NULL ELSE HomeCorners			END AS HomeCorners
	,CASE WHEN AwayCorners		='NULL' THEN NULL ELSE AwayCorners			END AS AwayCorners
	,CASE WHEN HomeYellow		='NULL' THEN NULL ELSE HomeYellow			END AS HomeYellow
	,CASE WHEN AwayYellow		='NULL' THEN NULL ELSE AwayYellow			END AS AwayYellow
	,CASE WHEN HomeRed			='NULL' THEN NULL ELSE HomeRed				END AS HomeRed
	,CASE WHEN AwayRed			='NULL' THEN NULL ELSE AwayRed				END AS AwayRed
	,CASE WHEN B365H			='NULL' THEN NULL ELSE B365H				END AS B365H
	,CASE WHEN B365D			='NULL' THEN NULL ELSE B365D				END AS B365D
	,CASE WHEN B365A			='NULL' THEN NULL ELSE B365A				END AS B365A
	,CASE WHEN BWH				='NULL' THEN NULL ELSE BWH					END AS BWH
	,CASE WHEN BWD				='NULL' THEN NULL ELSE BWD					END AS BWD
	,CASE WHEN BWA				='NULL' THEN NULL ELSE BWA					END AS BWA
	,CASE WHEN IWH				='NULL' THEN NULL ELSE IWH					END AS IWH
	,CASE WHEN IWD				='NULL' THEN NULL ELSE IWD					END AS IWD
	,CASE WHEN IWA				='NULL' THEN NULL ELSE IWA					END AS IWA
	,CASE WHEN LBH				='NULL' THEN NULL ELSE LBH					END AS LBH
	,CASE WHEN LBD				='NULL' THEN NULL ELSE LBD					END AS LBD
	,CASE WHEN LBA				='NULL' THEN NULL ELSE LBA					END AS LBA
	,CASE WHEN PSH				='NULL' THEN NULL ELSE PSH					END AS PSH
	,CASE WHEN PSD				='NULL' THEN NULL ELSE PSD					END AS PSD
	,CASE WHEN PSA				='NULL' THEN NULL ELSE PSA					END AS PSA
	,CASE WHEN WHH				='NULL' THEN NULL ELSE WHH					END AS WHH
	,CASE WHEN WHD				='NULL' THEN NULL ELSE WHD					END AS WHD
	,CASE WHEN WHA				='NULL' THEN NULL ELSE WHA					END AS WHA
	,CASE WHEN VCH				='NULL' THEN NULL ELSE VCH					END AS VCH
	,CASE WHEN VCD				='NULL' THEN NULL ELSE VCD					END AS VCD
	,CASE WHEN VCA				='NULL' THEN NULL ELSE VCA					END AS VCA
	,CASE WHEN Bb1X2			='NULL' THEN NULL ELSE Bb1X2				END AS Bb1X2
	,CASE WHEN BbMxH			='NULL' THEN NULL ELSE BbMxH				END AS BbMxH
	,CASE WHEN BbAvH			='NULL' THEN NULL ELSE BbAvH				END AS BbAvH
	,CASE WHEN BbMxD			='NULL' THEN NULL ELSE BbMxD				END AS BbMxD
	,CASE WHEN BbAvD			='NULL' THEN NULL ELSE BbAvD				END AS BbAvD
	,CASE WHEN BbMxA			='NULL' THEN NULL ELSE BbMxA				END AS BbMxA
	,CASE WHEN BbAvA			='NULL' THEN NULL ELSE BbAvA				END AS BbAvA
	,CASE WHEN BbOU				='NULL' THEN NULL ELSE BbOU					END AS BbOU
	,CASE WHEN BbMx_2_5			='NULL' THEN NULL ELSE BbMx_2_5				END AS BbMx_2_5
	,CASE WHEN BbAv_2_5			='NULL' THEN NULL ELSE BbAv_2_5				END AS BbAv_2_5
	,CASE WHEN BbMx_2_5_2		='NULL' THEN NULL ELSE BbMx_2_5_2			END AS BbMx_2_5_2
	,CASE WHEN BbAv_2_5_2		='NULL' THEN NULL ELSE BbAv_2_5_2			END AS BbAv_2_5_2
	,CASE WHEN BbAH				='NULL' THEN NULL ELSE BbAH					END AS BbAH
	,CASE WHEN BbAHh			='NULL' THEN NULL ELSE BbAHh				END AS BbAHh
	,CASE WHEN BbMxAHH			='NULL' THEN NULL ELSE BbMxAHH				END AS BbMxAHH
	,CASE WHEN BbAvAHH			='NULL' THEN NULL ELSE BbAvAHH				END AS BbAvAHH
	,CASE WHEN BbMxAHA			='NULL' THEN NULL ELSE BbMxAHA				END AS BbMxAHA
	,CASE WHEN BbAvAHA			='NULL' THEN NULL ELSE BbAvAHA				END AS BbAvAHA
	,CASE WHEN PSCH				='NULL' THEN NULL ELSE PSCH					END AS PSCH
	,CASE WHEN PSCD				='NULL' THEN NULL ELSE PSCD					END AS PSCD
	,CASE WHEN PSCA				='NULL' THEN NULL ELSE PSCA					END AS PSCA
FROM
    {{source('football_land', 'football_countries_union')}}